### ISSUE TITLE
SplitFactoryBuilder does not work in localhost test mode when explicitly configuring a yaml file.

### ISSUE THREAD

**Issue by salvisbh** [splitio/java-client#84]
With version 3.1.0 of the java-client it is no longer possible to use `SplitFactoryBuilder.local(myTestFilePath)` 
Instead, a new SplitClientConfig instance must be passed to the local - static method. In our CD environment we have to be able to set the path for the local test file, because we cannot store a configuration file in the userhome during the test.
No client can be created with configured split.yaml, regardless of whether the path is configured absolute or relative with
 
`SplitClientConfig.builder()
.splitFile("Testsplits.yaml")
.build();`
 
The following error is written to the log:

`java.io.FileNotFoundException: \C:\ieu\Projects\GITHUB\splitio\java-client\client\target\test-classes\split.yaml (The filename, directory name, or volume label syntax is incorrect)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at io.split.client.YamlLocalhostSplitFile.readOnSplits(YamlLocalhostSplitFile.java:27)
	at io.split.client.LocalhostSplitFactory.<init>(LocalhostSplitFactory.java:46)
	at io.split.client.LocalhostSplitFactory.createLocalhostSplitFactory(LocalhostSplitFactory.java:32)
	at io.split.client.SplitFactoryBuilder.local(SplitFactoryBuilder.java:70)
	at io.split.client.SplitFactoryBuilderTest.localhostModeWithAbsolutePathYaml(SplitFactoryBuilderTest.java:44)`

Test for reproducing the Exception:
`public class SplitFactoryBuilderTest {

    @Test
    public void localhostModeWithRelativePathYaml() throws IOException {

        //-- arrange

        //-- act
        SplitClientConfig clientConfig = SplitClientConfig.builder()
                .splitFile(SplitClientConfig.LOCALHOST_DEFAULT_FILE)
                .build();

        SplitFactory splitFactory = SplitFactoryBuilder.local(clientConfig);
        SplitClient client = splitFactory.client();

        //-- assert
        assertThat(client.getTreatment("user_a", "split_1"), is(equalTo("on")));
    }

    @Test
    public void localhostModeWithAbsolutePathYaml() throws Exception {

        //-- arrange
        URL testTogglesUrl = getClass().getClassLoader().getResource(SplitClientConfig.LOCALHOST_DEFAULT_FILE);
        String absolutePath = Paths.get(testTogglesUrl.toURI()).toFile().getAbsolutePath();

        //-- act
        SplitClientConfig clientConfig = SplitClientConfig.builder()
                .splitFile(absolutePath)
                .build();

        SplitFactory splitFactory = SplitFactoryBuilder.local(clientConfig);
        SplitClient client = splitFactory.client();

        //-- assert
        assertThat(client.getTreatment("user_a", "split_1"), is(equalTo("on")));
    }

}`

**Comment by patricioe** [comment]
@salvisbh we are looking into this and will get back to you shortly.

**Comment by patricioe** [comment]
In the mean time, I just wanted to make sure you are using the new format:


```yaml
- split_1:
   keys: user_b
   treatment: 'off'
   config: '{ "size" : 20 }'
- split_1:
   keys: [user_a]
   treatment: 'on'
- split_2:
   keys: user_b
   treatment: 'off'
   config: '{ "size" : 44 }'
- splitWithKeys:
   keys: [user_1, user_2, user_3]
   treatment: 'v1'
   config: '{ "size" : 44 }'
- splitWithNoKeys:
   treatment: 'v2'
   config: '{ "size" : 999 }'
```

We are in the process of updating the documentation to reflect this new format. Legacy format should still work though.
